ALTER TABLE `growth_stories` ADD `context` text DEFAULT '' NOT NULL;
ALTER TABLE `growth_stories` ADD `original_expression` text DEFAULT '' NOT NULL;
ALTER TABLE `growth_stories` ADD `suggested_reframe` text DEFAULT '' NOT NULL;
ALTER TABLE `growth_stories` ADD `reframe_choice` text DEFAULT 'keep_original' NOT NULL;
ALTER TABLE `growth_stories` ADD `evidence_kind` text DEFAULT 'other' NOT NULL;
ALTER TABLE `growth_stories` ADD `evidence_status` text DEFAULT 'self_reported' NOT NULL;
ALTER TABLE `growth_stories` ADD `updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL;

CREATE TABLE `teach_project_threads` (`id` text PRIMARY KEY NOT NULL, `owner_user_id` text NOT NULL, `circle_id` text, `title` text NOT NULL, `summary` text NOT NULL, `status` text DEFAULT 'active' NOT NULL, `visibility` text DEFAULT 'private' NOT NULL, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, `updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`owner_user_id`) REFERENCES `users`(`id`));
CREATE INDEX `teach_project_threads_owner_idx` ON `teach_project_threads` (`owner_user_id`,`updated_at`);
CREATE INDEX `teach_project_threads_circle_idx` ON `teach_project_threads` (`circle_id`);
CREATE TABLE `teach_project_entries` (`id` text PRIMARY KEY NOT NULL, `project_id` text NOT NULL, `contributor_user_id` text NOT NULL, `kind` text NOT NULL, `label` text NOT NULL, `reflection` text DEFAULT '' NOT NULL, `reference` text DEFAULT '' NOT NULL, `status` text DEFAULT 'active' NOT NULL, `occurred_at` text NOT NULL, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`project_id`) REFERENCES `teach_project_threads`(`id`), FOREIGN KEY (`contributor_user_id`) REFERENCES `users`(`id`));
CREATE INDEX `teach_project_entries_project_idx` ON `teach_project_entries` (`project_id`,`occurred_at`);
CREATE INDEX `teach_project_entries_contributor_idx` ON `teach_project_entries` (`contributor_user_id`);
CREATE TABLE `teach_circles` (`id` text PRIMARY KEY NOT NULL, `owner_user_id` text NOT NULL, `organization_id` text, `course_id` text, `kind` text NOT NULL, `title` text NOT NULL, `purpose` text NOT NULL, `visibility` text DEFAULT 'private' NOT NULL, `membership_mode` text DEFAULT 'invite_only' NOT NULL, `status` text DEFAULT 'active' NOT NULL, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, `updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`owner_user_id`) REFERENCES `users`(`id`), FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`), FOREIGN KEY (`course_id`) REFERENCES `teach_courses`(`id`));
CREATE INDEX `teach_circles_owner_idx` ON `teach_circles` (`owner_user_id`);
CREATE INDEX `teach_circles_organization_idx` ON `teach_circles` (`organization_id`);
CREATE TABLE `teach_circle_memberships` (`id` text PRIMARY KEY NOT NULL, `circle_id` text NOT NULL, `user_id` text NOT NULL, `role` text DEFAULT 'member' NOT NULL, `status` text DEFAULT 'active' NOT NULL, `joined_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`circle_id`) REFERENCES `teach_circles`(`id`), FOREIGN KEY (`user_id`) REFERENCES `users`(`id`));
CREATE INDEX `teach_circle_memberships_user_idx` ON `teach_circle_memberships` (`user_id`);
CREATE UNIQUE INDEX `teach_circle_memberships_unique_idx` ON `teach_circle_memberships` (`circle_id`,`user_id`);
CREATE TABLE `teach_recognitions` (`id` text PRIMARY KEY NOT NULL, `issuer_user_id` text NOT NULL, `recipient_user_id` text NOT NULL, `circle_id` text, `category` text NOT NULL, `statement` text NOT NULL, `context` text DEFAULT '' NOT NULL, `evidence_ref` text NOT NULL, `status` text DEFAULT 'pending_recipient_review' NOT NULL, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, `reviewed_at` text, FOREIGN KEY (`issuer_user_id`) REFERENCES `users`(`id`), FOREIGN KEY (`recipient_user_id`) REFERENCES `users`(`id`), FOREIGN KEY (`circle_id`) REFERENCES `teach_circles`(`id`));
CREATE INDEX `teach_recognitions_recipient_idx` ON `teach_recognitions` (`recipient_user_id`,`created_at`);
CREATE INDEX `teach_recognitions_circle_idx` ON `teach_recognitions` (`circle_id`);
CREATE TABLE `teach_recaps` (`id` text PRIMARY KEY NOT NULL, `user_id` text NOT NULL, `period` text NOT NULL, `period_start` text NOT NULL, `period_end` text NOT NULL, `payload` text NOT NULL, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`user_id`) REFERENCES `users`(`id`));
CREATE INDEX `teach_recaps_user_period_idx` ON `teach_recaps` (`user_id`,`period`,`period_start`);
CREATE UNIQUE INDEX `teach_recaps_unique_idx` ON `teach_recaps` (`user_id`,`period`,`period_start`,`period_end`);
CREATE TABLE `teach_organization_scopes` (`id` text PRIMARY KEY NOT NULL, `parent_organization_id` text NOT NULL, `child_organization_id` text NOT NULL, `kind` text DEFAULT 'commission_school' NOT NULL, `status` text DEFAULT 'active' NOT NULL, `valid_from` text NOT NULL, `valid_until` text, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`parent_organization_id`) REFERENCES `organizations`(`id`), FOREIGN KEY (`child_organization_id`) REFERENCES `organizations`(`id`));
CREATE INDEX `teach_organization_scopes_parent_idx` ON `teach_organization_scopes` (`parent_organization_id`);
CREATE UNIQUE INDEX `teach_organization_scopes_unique_idx` ON `teach_organization_scopes` (`parent_organization_id`,`child_organization_id`,`kind`);
