CREATE TABLE `teach_exceptional_access_requests` (`id` text PRIMARY KEY NOT NULL, `requester_user_id` text NOT NULL, `subject_user_id` text NOT NULL, `organization_id` text NOT NULL, `scope` text NOT NULL, `justification` text NOT NULL, `incident_reference` text NOT NULL, `status` text DEFAULT 'pending_approvals' NOT NULL, `expires_at` text NOT NULL, `approved_at` text, `denied_at` text, `used_at` text, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, `updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`requester_user_id`) REFERENCES `users`(`id`), FOREIGN KEY (`subject_user_id`) REFERENCES `users`(`id`), FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`));
CREATE INDEX `teach_exceptional_access_requester_idx` ON `teach_exceptional_access_requests` (`requester_user_id`,`created_at`);
CREATE INDEX `teach_exceptional_access_subject_idx` ON `teach_exceptional_access_requests` (`subject_user_id`,`created_at`);
CREATE INDEX `teach_exceptional_access_status_idx` ON `teach_exceptional_access_requests` (`organization_id`,`status`,`expires_at`);
CREATE TABLE `teach_exceptional_access_approvals` (`id` text PRIMARY KEY NOT NULL, `request_id` text NOT NULL, `approver_user_id` text NOT NULL, `decision` text NOT NULL, `rationale` text NOT NULL, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`request_id`) REFERENCES `teach_exceptional_access_requests`(`id`), FOREIGN KEY (`approver_user_id`) REFERENCES `users`(`id`));
CREATE INDEX `teach_exceptional_access_approval_request_idx` ON `teach_exceptional_access_approvals` (`request_id`,`created_at`);
CREATE UNIQUE INDEX `teach_exceptional_access_approval_actor_idx` ON `teach_exceptional_access_approvals` (`request_id`,`approver_user_id`);
CREATE TABLE `teach_exceptional_access_audit_events` (`id` text PRIMARY KEY NOT NULL, `request_id` text NOT NULL, `actor_user_id` text NOT NULL, `event_type` text NOT NULL, `event_digest` text NOT NULL, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`request_id`) REFERENCES `teach_exceptional_access_requests`(`id`), FOREIGN KEY (`actor_user_id`) REFERENCES `users`(`id`));
CREATE INDEX `teach_exceptional_access_audit_request_idx` ON `teach_exceptional_access_audit_events` (`request_id`,`created_at`);
