const contract = {
  openapi: "3.1.0",
  info: {
    title: "Scholarium API",
    version: "1.0.0",
    description: "Canonical /api/v1 contracts for the Scholarium scientific and educational community. Legacy unversioned resource routes remain temporary compatibility aliases only.",
  },
  servers: [{ url: "/" }],
  paths: {
    "/api/v1/openapi.json": { get: { summary: "Read the canonical OpenAPI contract for the current public API version" } },
    "/api/v1/account": { get: { summary: "Read the signed-in Scholarium account" } },
    "/api/v1/account/export": { get: { summary: "Download a private portable export of the signed-in account" } },
    "/api/v1/archive-manifests": { get: { summary: "Read owner-only archive manifests" }, post: { summary: "Register an owner-controlled external archive location without secrets" }, put: { summary: "Request archive restore or resynchronization" } },
    "/api/v1/accessibility-preferences": { get: { summary: "Read persisted private accessibility preferences" }, put: { summary: "Persist keyboard, motion, and screen-reader preferences" } },
    "/api/v1/author-identifiers": { get: { summary: "Read private author identifiers" }, put: { summary: "Save a checksum-validated self-claimed ORCID iD" }, delete: { summary: "Remove a private ORCID claim" } },
    "/api/v1/orcid-guidance": { get: { summary: "Read free ORCID registration and authentication guidance" } },
    "/api/v1/collections": { get: { summary: "List private personal reading collections" }, post: { summary: "Create a private personal collection" }, delete: { summary: "Delete an owner-owned private collection" } },
    "/api/v1/developer-seed": { get: { summary: "Read the public Scholarium Seed Protocol manifest without secrets or a ranking formula" } },
    "/api/v1/collection-items": { get: { summary: "List saved public work inside one owner-owned collection" }, put: { summary: "Save eligible public work to a private reading list or collection" }, delete: { summary: "Remove one saved work item" } },
    "/api/v1/health": { get: { summary: "Read service health" } },
    "/api/v1/teach/lesson": { get: { summary: "Read the public Spanish starter lesson contract" }, post: { summary: "Record a signed-in learner attempt and exact checkpoint" } },
    "/api/v1/teach/strengths": { get: { summary: "Read private contestable strength observations" }, post: { summary: "Create a declared, observed, or proposed strength observation" }, put: { summary: "Accept, contest, or expire an owned strength observation" }, delete: { summary: "Delete an owned strength observation" } },
    "/api/v1/teach/media": { get: { summary: "Read private Teach media requests and daily limits" }, post: { summary: "Prepare a user-triggered, source-bound video or podcast request" } },
    "/api/v1/teach/media/publication": { post: { summary: "Record a separate owner confirmation for one rendered artifact and external destination without publishing it" } },
    "/api/v1/teach/consents": { get: { summary: "Read separate Teach purpose consents" }, put: { summary: "Grant one Teach purpose consent" }, delete: { summary: "Revoke one Teach purpose consent" } },
    "/api/v1/teach/data": { delete: { summary: "Delete the signed-in account's Teach-domain data while retaining the base Scholarium account" } },
    "/api/v1/teach/knowledge-gateway": { post: { summary: "Validate a stateless education-plugin graph delta and compute preparation-only graph, Eulerian, and Hilbert-location evidence" } },
    "/api/v1/teach/gate5": { post: { summary: "Create a signed, expiring and pseudonymous private-worker outbox request" } },
    "/api/v1/teach/gate5/worker": { get: { summary: "Read a bounded pseudonymous batch as an authenticated private worker" }, post: { summary: "Submit a terminal worker receipt with an independently verified Ed25519 signature" } },
    "/api/v1/teach/life-science/router": { post: { summary: "Select the smallest installed Life Science primary-source tool set for a bounded educational question" } },
    "/api/v1/teach/assistant/student": { get: { summary: "Read the signed-in learner's private assistant graph, weekly objectives, and intervention preferences" }, post: { summary: "Create a private, provenance-bound learner assistant graph record" }, delete: { summary: "Delete an owned learner assistant graph record" } },
    "/api/v1/teach/assistant/teacher": { get: { summary: "Read course-authorized bounded pedagogical summaries without raw answers or private learner graphs" } },
    "/api/v1/teach/assistant/admin": { get: { summary: "Read authorized school aggregates subject to minimum-cohort suppression" } },
    "/api/v1/teach/assistant/exchanges": { get: { summary: "Read unexpired bounded assistant exchange receipts" }, post: { summary: "Prepare a consent-bound, expiring, idempotent assistant projection" }, put: { summary: "Acknowledge receipt of an unexpired assistant projection" } },
    "/api/v1/teach/goals": { get: { summary: "Read the learner's weekly objectives" }, post: { summary: "Create or update a school-year-bound weekly objective" }, delete: { summary: "Delete an owned weekly objective" } },
    "/api/v1/teach/interventions": { get: { summary: "Read learner-controlled intervention frequency, context, and silence preferences" }, put: { summary: "Update intervention and silence preferences without hidden monitoring" } },
    "/api/v1/teach/projects": { get: { summary: "Read authorized project threads with milestones, versions, files, sources, and contributions" }, post: { summary: "Create a private, circle, or public project thread" }, delete: { summary: "Delete an owner-controlled project thread" } },
    "/api/v1/teach/projects/entries": { post: { summary: "Add a milestone, version, file, source, or contribution to an authorized project" }, delete: { summary: "Delete an owner- or contributor-controlled project entry" } },
    "/api/v1/teach/circles": { get: { summary: "Read learning circles where the signed-in account is an owner or member" }, post: { summary: "Create a class, team, music, art, interest, or peer-support circle" }, put: { summary: "Invite a member to an owner-controlled circle" } },
    "/api/v1/teach/recognitions": { get: { summary: "Read private evidence-bound recognitions received by the learner" }, post: { summary: "Create a non-ranked recognition inside a shared circle" }, put: { summary: "Accept, contest, or expire a received recognition" } },
    "/api/v1/teach/recaps": { post: { summary: "Build and persist a weekly, monthly, or quarterly evidence recap" } },
    "/api/v1/teach/dashboard/student": { get: { summary: "Read the learner's notions, reminders, strengths, projects, proofs, recognitions, and objectives" } },
    "/api/v1/teach/dashboard/teacher": { get: { summary: "Read course-authorized pseudonymous objectives, confusions, strategies, and intervention states" } },
    "/api/v1/teach/dashboard/organization": { get: { summary: "Read school or commission aggregates with minimum-cohort suppression and no individual identifiers" } },
    "/api/v1/algoquest/events": { get: { summary: "Read private AlgoQuest learning events" }, post: { summary: "Create an idempotent, purpose-bound AlgoQuest event" } },
    "/api/v1/growth-stories": { get: { summary: "Read the signed-in learner's growth stories" }, post: { summary: "Create an evidence-bound growth capsule and, when explicitly eligible, its public growth_story publication" } },
    "/api/v1/artifacts": { get: { summary: "List or download active artifacts attached to a public publication" }, post: { summary: "Upload a hashed scholarly artifact" } },
    "/api/v1/academia-migrations": { get: { summary: "Read private owner-confirmed Academia.edu migration drafts" }, post: { summary: "Create a private review draft or import selected owner-confirmed items" } },
    "/api/v1/feed-feedback": { put: { summary: "Save an explicit private favorite or less-like-this feed preference" } },
    "/api/v1/funding-campaigns": { get: { summary: "Read owner funding campaign drafts and provider-setup state" }, post: { summary: "Create a campaign or provider-bound contribution intent without storing funds" } },
    "/api/v1/guardian-consents": { get: { summary: "Read private guardian consent records without exposing other identities" }, post: { summary: "Request scoped guardian consent" }, put: { summary: "Activate a pending guardian consent after guardian verification" }, delete: { summary: "Revoke a guardian consent" } },
    "/api/v1/integrations": { get: { summary: "List consent-first integrations" }, post: { summary: "Prepare an explicit provider consent flow" } },
    "/api/v1/provider-capabilities": { get: { summary: "Read public provider capability and authority-boundary contracts" } },
    "/api/v1/provider-consents": { get: { summary: "Read private provider consent records" }, put: { summary: "Record explicit provider scope consent without storing provider credentials" }, delete: { summary: "Revoke one provider consent record" } },
    "/api/v1/webauth-handoff-requests": { get: { summary: "Read private official WebAuth handoff records" }, post: { summary: "Prepare a consent-gated Codex or Antigravity provider handoff without forwarding credentials" } },
    "/api/v1/local-insights": { get: { summary: "Read the device-local-only privacy analytics contract" } },
    "/api/v1/live-sessions": { get: { summary: "Read owner-only educational Live plans" }, post: { summary: "Plan an educational Live without stream keys or raw chat" } },
    "/api/v1/media-links": { get: { summary: "Read public external media links for a publication" }, post: { summary: "Link an author-owned YouTube or TikTok URL without copying the video" } },
    "/api/v1/media-webhook-events": { get: { summary: "Read the signed-in owner's minimal YouTube callback delivery trace" } },
    "/api/v1/payments/paypal/order": { get: { summary: "Read the PayPal checkout capability without credentials" }, post: { summary: "Create a fixed verified-contributor PayPal order" } },
    "/api/v1/payments/paypal/return": { get: { summary: "Capture one approved PayPal order server-side and redirect the signed-in contributor back to the app" } },
    "/api/v1/project-starter": { get: { summary: "Read private project starter requests" }, post: { summary: "Prepare a provider-gated private project from an attributed source repository without writing to the maintainer repository" } },
    "/api/v1/quantech-render-request": {
      get: { summary: "List the signed-in author's private QuaNTecH-ViD handoff history without raw scripts, media, or provider secrets" },
      post: { summary: "Prepare a minimal QuaNTecH-ViD provider handoff without uploading media or forwarding raw script text" },
    },
    "/api/v1/webhooks/paypal": { post: { summary: "Verify and reconcile a minimal PayPal payment notification" } },
    "/api/v1/repository-links": { get: { summary: "Read public attributed source-repository links for a publication" }, post: { summary: "Link an author-owned GitHub, GitLab, or SourceForge repository without copying code" } },
    "/api/v1/webhooks/youtube": { get: { summary: "Verify a configured YouTube PubSubHubbub callback" }, post: { summary: "Record an HMAC-authenticated YouTube Atom update for a linked channel" } },
    "/api/v1/notification-preferences": { get: { summary: "Read persisted private notification preferences" }, put: { summary: "Persist digest, topic, moderation, and channel preferences" } },
    "/api/v1/onboarding": { post: { summary: "Create a role-aware account" } },
    "/api/v1/profile-media": { get: { summary: "Read private media or an owner-enabled public avatar/banner" }, post: { summary: "Store a validated private avatar or profile banner" } },
    "/api/v1/profile-preferences": { get: { summary: "Read private profile appearance and visibility preferences" }, put: { summary: "Update profile appearance and explicit public-profile visibility" } },
    "/api/v1/profile-sections": { get: { summary: "Read private profile sections or owner-enabled public profile context" }, post: { summary: "Create an author-controlled profile section" }, put: { summary: "Update one author-controlled profile section" }, delete: { summary: "Delete one author-controlled profile section" } },
    "/api/v1/public-profiles/{publicId}": { get: { summary: "Read an owner-enabled public profile and already-public work" } },
    "/api/v1/author-metrics": { get: { summary: "Read transparent first-party public author metrics without readership or citation claims" } },
    "/api/v1/publications": {
      get: { summary: "List public publications" },
      post: { summary: "Create a versioned publication and provenance receipt" },
    },
    "/api/v1/publication-moderation": { get: { summary: "Read minimal automated moderation reason codes for an author-owned publication" } },
    "/api/v1/publication-relationships": { get: { summary: "Read public author-declared source relationships" }, post: { summary: "Declare a source, translation, version, import, or citation relationship for owned work" } },
    "/api/v1/provenance/verify": { get: { summary: "Read a public provenance receipt for one public version" }, post: { summary: "Recalculate a public version hash without storing submitted content" } },
    "/api/v1/search": { get: { summary: "Search public research publications with explicit lexical reasons and filters" } },
    "/api/v1/search-alerts": { get: { summary: "Read private explicit search alert preferences" }, post: { summary: "Create a private query or topic alert preference" }, delete: { summary: "Delete a private search alert preference" } },
    "/api/v1/citation-alerts": { get: { summary: "Read private author citation alert preferences without third-party citation claims" }, post: { summary: "Enable an author-owned publication citation alert preference" }, delete: { summary: "Remove an author-owned publication citation alert preference" } },
    "/api/v1/scholar-indexing-status": { get: { summary: "Read Scholarium-controlled crawler prerequisites for one public publication without claiming external indexing" } },
    "/api/v1/scientific-deposits": { get: { summary: "Read private Zenodo or DOI deposit drafts" }, post: { summary: "Prepare a scientific deposit request without OAuth tokens, DOI reservation, or publication" } },
    "/api/v1/video-production-plan": { post: { summary: "Create an ephemeral, author-led podcast or video production brief without uploading media" } },
    "/api/v1/publications/{publicationId}/versions": { get: { summary: "Read the immutable public version history" }, post: { summary: "Create a new author-owned publication version from the current version" } },
    "/api/v1/publication-interactions": {
      get: { summary: "Read public reactions and version-bound comments" },
      post: { summary: "Create an academic reaction, limited-depth comment, report, block, or mute" },
      delete: { summary: "Remove the signed-in account's reaction" },
    },
    "/api/v1/quanthor-formalization": { get: { summary: "List educational formalization templates" }, post: { summary: "Create a non-blocking QuaNthoR outline" } },
    "/api/v1/ranking-preferences": {
      get: { summary: "Read user-controlled ranking preferences" },
      put: { summary: "Update bounded ranking weights" },
    },
    "/api/v1/topic-follows": {
      get: { summary: "List the signed-in account's followed topics" },
      put: { summary: "Follow a topic without affecting paid reach" },
      delete: { summary: "Stop following one topic" },
    },
    "/api/v1/translation-preferences": { get: { summary: "Read persisted private language and translation preferences" }, put: { summary: "Persist original-canonical translation preferences and glossary terms" } },
    "/api/v1/user-follows": { get: { summary: "List authors explicitly followed by the signed-in account" }, put: { summary: "Follow one public author without exposing provider identity" }, delete: { summary: "Stop following one public author" } },
    "/api/v1/verified-subscription": {
      get: { summary: "Read the fixed-price verified contributor plan and its zero-ranking-effect contract" },
      post: { summary: "Prepare a verified contributor subscription state after identity and passkey verification" },
    },
  },
  components: {
    schemas: {
      Gate5AdapterEnvelope: {
        type: "object",
        description: "Signed, expiring and pseudonymous adapter envelope. Raw user and tenant identifiers are excluded.",
        required: ["schema", "requestId", "target", "purpose", "expiresAt", "privacy", "signature"],
        properties: {
          schema: { type: "string", const: "scholarium.gate5-adapter-envelope.v1" },
          requestId: { type: "string", minLength: 1 },
          target: { type: "string", enum: ["synthia", "memory-lake", "hipporag", "fnp-qnn", "quantech-vid"] },
          purpose: { type: "string", minLength: 1 },
          expiresAt: { type: "string", format: "date-time" },
          privacy: {
            type: "object",
            required: ["rawIdentityIncluded", "externalAdapterReceivesUserId", "crossTenantLookupAllowed"],
            properties: {
              rawIdentityIncluded: { type: "boolean", const: false },
              externalAdapterReceivesUserId: { type: "boolean", const: false },
              crossTenantLookupAllowed: { type: "boolean", const: false },
            },
          },
          signature: { type: "string", minLength: 1 },
        },
      },
    },
  },
};

export function GET() {
  return Response.json(contract, { headers: { "cache-control": "public, max-age=3600" } });
}
